import Link from 'next/link';
import Image from 'next/image';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { CheckCircle, Zap, BrainCircuit } from 'lucide-react';
import { PlaceHolderImages } from '@/lib/placeholder-images';

export default function Home() {
  const features = [
    {
      icon: <Zap className="h-6 w-6 text-primary" />,
      title: 'AI-Powered Question Generation',
      description: 'Get unique mock tests generated by AI, tailored to your exam, subject, and difficulty level.',
    },
    {
      icon: <BrainCircuit className="h-6 w-6 text-primary" />,
      title: 'Personalized Feedback',
      description: 'Receive detailed explanations for every question and actionable tips to improve your weak areas.',
    },
    {
      icon: <CheckCircle className="h-6 w-6 text-primary" />,
      title: 'Realistic Exam Simulation',
      description: 'Experience a test environment that mimics actual government exam portals for better preparation.',
    },
  ];

  const heroImage = PlaceHolderImages.find(p => p.id === "hero-image");

  return (
    <div className="container mx-auto px-4 py-8 md:py-12">
      <section className="text-center">
        <h1 className="text-4xl font-bold tracking-tight text-foreground sm:text-5xl md:text-6xl font-headline">
          Master Your Exams with <span className="text-primary">Vidyarthi Vista</span>
        </h1>
        <p className="mt-6 max-w-2xl mx-auto text-lg leading-8 text-muted-foreground">
          Your ultimate companion for cracking Indian government exams. Generate unlimited AI-powered mock tests and get personalized insights to boost your score.
        </p>
        <div className="mt-10 flex items-center justify-center gap-x-6">
          <Button asChild size="lg">
            <Link href="/test/new">Start a New Mock Test</Link>
          </Button>
          <Button asChild variant="outline" size="lg">
            <Link href="/history">View Test History</Link>
          </Button>
        </div>
      </section>

      <section className="mt-20">
        <div className="relative isolate overflow-hidden rounded-2xl border bg-card shadow-lg">
           {heroImage && (
             <Image
              src={heroImage.imageUrl}
              alt={heroImage.description}
              width={1200}
              height={600}
              className="w-full h-auto object-cover"
              data-ai-hint={heroImage.imageHint}
              priority
            />
           )}
           <div className="absolute inset-0 bg-gradient-to-t from-background via-background/60 to-transparent" />
        </div>
      </section>
      
      <section className="mt-20">
        <div className="mx-auto max-w-7xl">
          <h2 className="text-3xl font-bold text-center mb-10 font-headline">Why Choose Us?</h2>
          <div className="grid grid-cols-1 gap-8 md:grid-cols-3">
            {features.map((feature, index) => (
              <Card key={index} className="flex flex-col">
                <CardHeader className="flex-shrink-0">
                  <div className="flex items-center gap-4">
                    {feature.icon}
                    <CardTitle>{feature.title}</CardTitle>
                  </div>
                </CardHeader>
                <CardContent className="flex-grow">
                  <CardDescription>{feature.description}</CardDescription>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}
